export const translations = {
  en: {
    title: "Contact Us",
    subtitle: "We’d love to hear from you. Reach out with questions or support requests.",
    form: {
      name: "Name",
      namePlaceholder: "Enter your full name",
      email: "Email",
      emailPlaceholder: "Enter your email address",
      message: "Message",
      messagePlaceholder: "Type your message here",
      submit: "Send Message",
    },
    contact: {
      title: "Get in Touch",
      description: "Our team is ready to answer your questions and support you in any way we can.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      addressLabel: "Address",
      address: "123 Human Rights Ave, Global City",
    },
    mapPlaceholder: "Map will appear here",
  },
  hi: {
    title: "संपर्क करें",
    subtitle: "हमें आपसे सुनकर खुशी होगी। प्रश्न या समर्थन अनुरोध भेजें।",
    form: {
      name: "नाम",
      namePlaceholder: "अपना पूरा नाम दर्ज करें",
      email: "ईमेल",
      emailPlaceholder: "अपना ईमेल पता दर्ज करें",
      message: "संदेश",
      messagePlaceholder: "अपना संदेश यहाँ लिखें",
      submit: "संदेश भेजें",
    },
    contact: {
      title: "संपर्क करें",
      description: "हमारी टीम आपके प्रश्नों का उत्तर देने और किसी भी प्रकार से मदद करने के लिए तैयार है।",
      emailLabel: "ईमेल",
      phoneLabel: "फ़ोन",
      addressLabel: "पता",
      address: "123 मानवाधिकार एवेन्यू, ग्लोबल सिटी",
    },
    mapPlaceholder: "मैप यहाँ दिखाई देगा",
  },
  fr: {
    title: "Contactez-nous",
    subtitle: "Nous serions ravis de vous entendre. Envoyez vos questions ou demandes de support.",
    form: {
      name: "Nom",
      namePlaceholder: "Entrez votre nom complet",
      email: "Email",
      emailPlaceholder: "Entrez votre adresse email",
      message: "Message",
      messagePlaceholder: "Tapez votre message ici",
      submit: "Envoyer le message",
    },
    contact: {
      title: "Entrer en contact",
      description: "Notre équipe est prête à répondre à vos questions et à vous soutenir de toutes les manières possibles.",
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      addressLabel: "Adresse",
      address: "123 Avenue des Droits de l'Homme, Ville Globale",
    },
    mapPlaceholder: "La carte apparaîtra ici",
  },
};
